import './globals.css'
import type { Metadata } from 'next'
import {fontTextII,fontTextI,fontTema,fontHello,inter} from '@/app/(utilites)/fonts'
import Link from 'next/link'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${fontHello.variable} ${fontTextII.variable} ${fontTextI.variable} ${fontTema.variable}`}>
        <header className='fixed z-50 w-screen shadow-md p-1 top-0 backdrop-blur-md'>
          
          <nav className={'flex justify-center'}>
            <ul className='flex w-fit align-middle'>
              <li><Link href={'#home'} className={'tu btn text-2xl'}>Home</Link></li>
              <li><Link href={'#about'} className='btn'>About me</Link></li>
              <li><Link href={'#skill'} className='btn'>Skills</Link></li>
              <li><Link href={'#project'} className='btn'>Projects</Link></li>
            </ul>
          </nav>
        </header>

        {children}

        <footer className='bg-gray-500 text-white text-lg p-2 bottom-0 flex justify-center'>
          <p>Copyright © 2023. Todos os direitos reservados.</p>
        </footer>
      </body>
    </html>
  )
}
